name: PMU Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # toutes les 5 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Installer Chrome
      - name: Setup Chrome
        uses: browser-tools/setup-chrome@v1

      # Installer ChromeDriver compatible
      - name: Setup ChromeDriver
        uses: actions/setup-chromedriver@v1
        with:
          chromedriver-version: 'latest'

      - name: Run Bot
        run: python bot.py
